### ISSUE TITLE
More granularity for Mudd/RBSC Hours

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/special_collections#462]
The daily calendar value displayed in the site footer currently only show the "rbsc" calendar entry. Occasionally Mudd and RBSC have different hours. The site should reflect this and show the mudd entry when you are visiting a page that starts with /mudd. The JS that generates this value from a daily hours data feed from the main website is https://github.com/pulibrary/rbsc_drupal/blob/5cdb62730d33c234e3690336d7f7891683e96321/sites/all/themes/rbsc/assets/source/scripts/rbsc.behaviors.js#L48.

**Comment by axamei** [comment]
Grab hours from libcal
