### ISSUE TITLE
Migrate mudd_exhibits

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/special_collections#516]
On the libwebprod server there are bunch of old static mudd exhibition websitesin /var/www/apps/mudd_exhibits. These need to be moved to libphp-prod and set up with proxy pass rules off the rbsc.princeton.edu domain at the top-level path of "mudd-exhibits".

**Comment by kevinreiss** [comment]
@carolyncole Should I put the exhibits we'd want to keep up on the lib-static file-system, store their content in a github repo, and file an issue for proxy pass rules to point them to a new home URL on library.princeton.edu.

**Comment by sandbergja** [comment]
@kevinreiss will this be included in the Drupal migration work that the vendor will do?

**Comment by kevinreiss** [comment]
Actually this was already done. 

https://github.com/pulibrary/mudd-exhibits
https://github.com/pulibrary/princeton_ansible/blob/7fe0331ff28c94acf41494e855c3894895faeb9c/roles/libstatic/defaults/main.yml#L59
