### ISSUE TITLE
Suppress / remove staff pages 

### ISSUE THREAD

**Issue by axamei** [pulibrary/special_collections#566]
Also remove from index.

https://library.princeton.edu/special-collections/staff/tatiana-celmare

> It appears as though our Special Collections web-site is drawing inactive information from a directory somewhere.  Sarah Hamerman describes a scenario below where someone was attempting to reach out to Tatiana Celmare, who left our employ last year.
>  
> Two questions:  
> ·         Can you help us remove Tatiana’s (she went by Adriana) information?
> ·         Is it possible to have this information draw and update from a more actively updated directory?
>  
> Thanks in advance,
> Darlene

**Comment by kevinreiss** [comment]
Staff pages removed some years ago.
