### ISSUE TITLE
Emails to libanswers.princeton.edu fail

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/special_collections#582]
Can we configure our relay to allow email to go from webforms to libanswers.princeton.edu?
https://library.princeton.edu/special-collections/senior-thesis-order-form - example

@axamei Mudd tells me that when they point this form to mudd@libanswers.princeton.edu it doesn't work?

**Comment by axamei** [comment]
@kevinreiss we need to add the smtp module like we did on the library main site to get this working.

**Comment by axamei** [comment]
This is now active and working on the production server
