### ISSUE TITLE
Some capistrano tasks are getting Operation: not permitted errors

### ISSUE THREAD

**Issue by axamei** [pulibrary/special_collections#591]
E.g., `drupal:set_permissions_for_runtime` is getting  `chmod: changing permissions of '/var/www/special_collections_cap/shared/tmp': Operation not permitted`

**Comment by axamei** [comment]
I am also noticing that the database updates (`drush updatedb`) are still pending / not run via deploy.

**Comment by carolyncole** [comment]
Since things are working we will close this issue.  We can revisit if we notice
