### ISSUE TITLE
FAQ Imports Not Running/Working

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/special_collections#621]
This example was brought to my attention:

https://library.princeton.edu/special-collections/faqs/how-do-i-access-f-scott-fitzgerald-papers-f-scott-fitzgerald-additional-papers-zelda-fitzgerald

https://faq.library.princeton.edu/rbsc/faq/303964?m=p

There is an importer set up to process entries in our libanswers FAQ to include these entries via an import through the API provided by Libanswers but it doesn't appear to actually be configured and running. At some point it must have been run. In theory FAQ answer should appear on the SC site. @sdellis @axamei does any of this ring a bell in your memories?

**Comment by axamei** [comment]
@kevinreiss does not ring a bell for me. it's not clear to me how this was set up. looks like that feature, rbsc_faq, was last updated 5 years ago. there is a faq importer content type called libanswers faqs importer. maybe this is the source? https://library.princeton.edu/special-collections/node/16473/log

**Comment by axamei** [comment]
No issues with FAQ importer. The LibAnswer FAQ content did not have the answer in the correct field.
