### ISSUE TITLE
Add Cap Command to Dump Database

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/special_collections#736]
Mysqldump requires users to have the FLUSH TABLES permissions which our non-root users do not have. Enable project the dump the database to work around issue https://github.com/pulibrary/princeton_ansible/issues/3690

## Implementation Notes

Implemented in the main website at: https://github.com/pulibrary/pul_library_drupal/pull/1967

**Comment by sandbergja** [comment]
Note that pas_craft has a cap task that dumps the db, and also downloads it to the local device: https://github.com/PrincetonUniversityLibrary/pas-craft3/blob/main/config/deploy.rb#L80-L90
