### ISSUE TITLE
`Special Collections Research Account` link is broken for (https://library.princeton.edu/special-collections/services/theses-dissertations)

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/special_collections#775]
I apologize if this is the wrong location to track Drupal/CMS content bugs, however, it was reported that the link `Special Collections Research Account` (https://lib-aeon.princeton.edu/aeon/Aeon.dll) seems to be breaking. Unfortunately, I have no knowledge of Aeon and how this URL should be structured. Please let me know if I can assist in any manner (I will just please need to request reference documentation for the Aeon URL parameters for creating this type of an account).

**Comment by ccleeton** [comment]
@jrgriffiniii we have this link a number of places. Where did you find this broken one?
